// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/timers.h"
#include "nvs_flash.h"
#include "esp_event.h"
#include "esp_netif.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_system.h"
#include "esp_now.h"
#include "esp_crc.h"
#include "espnow_example.h"

static const char *TAG = "Button1_Callback";

// extern uint8_t target_mac[];

// static const char *TAG = "Panel2";
// static uint8_t target_mac[ESP_NOW_ETH_ALEN] = {0x7C, 0xDF, 0xA1, 0xB8, 0xBE, 0xFC};

typedef enum
{
    MODE_A1,
    MODE_A2,
    MODE_B1,
    MODE_B2,
    MODE_C1,
    MODE_C2,
    NUM_MODES
} MessageMode;

MessageMode current_modes[NUM_MODES] = {
    MODE_A1, MODE_B1, MODE_C1};

int message_counters[NUM_MODES] = {0};

static void button_event_cb(lv_event_t *event, MessageMode mode, const char *message1, const char *message2)
{
    if (event->code == LV_EVENT_VALUE_CHANGED)
    {
        ESP_LOGI(TAG, "Button value changed");

        char send_buf[3];
         snprintf(send_buf, sizeof(send_buf), (message_counters[mode] % 2 == 0) ? message1 : message2);
        //snprintf(send_buf, sizeof(send_buf), "%s", (message_counters[mode] % 2 == 0) ? message1 : message2);

        if (esp_now_send(target_mac, (uint8_t *)send_buf, sizeof(send_buf)) != ESP_OK)
        {
            ESP_LOGE(TAG, "Send error");
        }

        // Increment message counter for the mode
        message_counters[mode]++;
    }
}
static void button4_event_cb(lv_event_t *event)
{
    button_event_cb(event, MODE_A1, "A1", "A2");
}


static void button2_event_cb(lv_event_t *event)
{
    button_event_cb(event, MODE_B1, "B1", "B2");
}
static void button1_event_cb(lv_event_t *event)
{
    button_event_cb(event, MODE_C1, "C1", "C2");
}






void ui_event_comp_Panel2_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_checked_set_text_value(comp_Panel2[UI_COMP_PANEL2_BUTTON1_LABEL1], target, "ON", "OFF");
    }
}
void ui_event_comp_Panel2_Button2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_checked_set_text_value(comp_Panel2[UI_COMP_PANEL2_BUTTON2_LABEL3], target, "ON", "OFF");
    }
}
void ui_event_comp_Panel2_Button4(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_checked_set_text_value(comp_Panel2[UI_COMP_PANEL2_BUTTON4_LABEL4], target, "ON", "OFF");
    }
}



void ui_event_comp_Panel2_Arc2(lv_event_t *e) // arc回调函数
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t **comp_Panel2 = lv_event_get_user_data(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(comp_Panel2[UI_COMP_PANEL2_ARC2_LABEL2], target, "", "%");
    }
}

// COMPONENT Panel2

lv_obj_t *ui_Panel2_create(lv_obj_t *comp_parent)
{

    lv_obj_t *cui_Panel2;
    cui_Panel2 = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel2, 300);
    lv_obj_set_height(cui_Panel2, 230);
    lv_obj_set_align(cui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t *cui_Button1;
    cui_Button1 = lv_btn_create(cui_Panel2);
    lv_obj_set_width(cui_Button1, 100);
    lv_obj_set_height(cui_Button1, 50);
    lv_obj_set_x(cui_Button1, 83);
    lv_obj_set_y(cui_Button1, 70);
    lv_obj_set_align(cui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(cui_Button1, LV_OBJ_FLAG_SCROLLABLE);                            /// Flags
    lv_obj_add_event_cb(cui_Button1, button1_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    lv_obj_t *cui_Label1;
    cui_Label1 = lv_label_create(cui_Button1);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "OFF");

    lv_obj_t *cui_Button2;
    cui_Button2 = lv_btn_create(cui_Panel2);
    lv_obj_set_width(cui_Button2, 100);
    lv_obj_set_height(cui_Button2, 50);
    lv_obj_set_x(cui_Button2, 83);
    lv_obj_set_y(cui_Button2, 0);
    lv_obj_set_align(cui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(cui_Button2, LV_OBJ_FLAG_SCROLLABLE);                            /// Flags
    lv_obj_add_event_cb(cui_Button2, button2_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    lv_obj_t *cui_Label3;
    cui_Label3 = lv_label_create(cui_Button2);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label3, "OFF");

    lv_obj_t *cui_Button4;
    cui_Button4 = lv_btn_create(cui_Panel2);
    lv_obj_set_width(cui_Button4, 100);
    lv_obj_set_height(cui_Button4, 50);
    lv_obj_set_x(cui_Button4, 83);
    lv_obj_set_y(cui_Button4, -71);
    lv_obj_set_align(cui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Button4, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(cui_Button4, LV_OBJ_FLAG_SCROLLABLE);                            /// Flags
    lv_obj_add_event_cb(cui_Button4, button4_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    lv_obj_t *cui_Label4;
    cui_Label4 = lv_label_create(cui_Button4);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "OFF");

    lv_obj_t *cui_Arc2;
    cui_Arc2 = lv_arc_create(cui_Panel2);
    lv_obj_set_width(cui_Arc2, 150);
    lv_obj_set_height(cui_Arc2, 150);
    lv_obj_set_x(cui_Arc2, -67);
    lv_obj_set_y(cui_Arc2, 1);
    lv_obj_set_align(cui_Arc2, LV_ALIGN_CENTER);

    lv_obj_t *cui_Label2;
    cui_Label2 = lv_label_create(cui_Arc2);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "50");

    lv_obj_t **children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL2_NUM);
    children[UI_COMP_PANEL2_PANEL2] = cui_Panel2;
    children[UI_COMP_PANEL2_BUTTON1] = cui_Button1;
    children[UI_COMP_PANEL2_BUTTON1_LABEL1] = cui_Label1;
    children[UI_COMP_PANEL2_BUTTON2] = cui_Button2;
    children[UI_COMP_PANEL2_BUTTON2_LABEL3] = cui_Label3;
    children[UI_COMP_PANEL2_BUTTON4] = cui_Button4;
    children[UI_COMP_PANEL2_BUTTON4_LABEL4] = cui_Label4;
    children[UI_COMP_PANEL2_ARC2] = cui_Arc2;
    children[UI_COMP_PANEL2_ARC2_LABEL2] = cui_Label2;
    lv_obj_add_event_cb(cui_Panel2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel2, del_component_child_event_cb, LV_EVENT_DELETE, children);

    lv_obj_add_event_cb(cui_Arc2, ui_event_comp_Panel2_Arc2, LV_EVENT_ALL, children);

    lv_obj_add_event_cb(cui_Button1, ui_event_comp_Panel2_Button1, LV_EVENT_CLICKED, children);
    lv_obj_add_event_cb(cui_Button2, ui_event_comp_Panel2_Button2, LV_EVENT_CLICKED, children);
    lv_obj_add_event_cb(cui_Button4, ui_event_comp_Panel2_Button4, LV_EVENT_ALL, children);

    ui_comp_Panel2_create_hook(cui_Panel2);
    return cui_Panel2;
}
/*
lv_obj_add_event_cb(cui_Panel2, del_component_child_event_cb, LV_EVENT_DELETE, children);
static void del_component_child_event_cb(lv_event_t *e) {
    lv_obj_t **children = lv_event_get_user_data(e);
    lv_mem_free(children);
}
*/