// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_PANEL2_H
#define _UI_COMP_PANEL2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel2
#define UI_COMP_PANEL2_PANEL2 0
#define UI_COMP_PANEL2_BUTTON1 1
#define UI_COMP_PANEL2_BUTTON1_LABEL1 1
#define UI_COMP_PANEL2_BUTTON2 2
#define UI_COMP_PANEL2_BUTTON2_LABEL3 2
#define UI_COMP_PANEL2_BUTTON4 4
#define UI_COMP_PANEL2_BUTTON4_LABEL4 4
#define UI_COMP_PANEL2_ARC2 5
#define UI_COMP_PANEL2_ARC2_LABEL2 6
#define _UI_COMP_PANEL2_NUM 7




lv_obj_t * ui_Panel2_create(lv_obj_t * comp_parent);
void ui_event_comp_Panel2_Arc2(lv_event_t * e);

void ui_event_comp_Panel2_Button1(lv_event_t *e);
// void ui_event_comp_Panel2_Button2(lv_event_t *e);
// void ui_event_comp_Panel2_Button4(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
