// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_PANEL2_H
#define _UI_COMP_PANEL2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel2
#define UI_COMP_PANEL2_PANEL2 0
#define UI_COMP_PANEL2_BUTTON2 1
#define UI_COMP_PANEL2_BUTTON2_LABEL2 2
#define UI_COMP_PANEL2_BUTTON1 3
#define UI_COMP_PANEL2_BUTTON1_LABEL1 4
#define _UI_COMP_PANEL2_NUM 5
lv_obj_t * ui_Panel2_create(lv_obj_t * comp_parent);
void ui_event_comp_Panel2_Button2(lv_event_t * e);
void ui_event_comp_Panel2_Button1(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
