// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
//
//void get_component_child_event_cb(lv_event_t * e);
//void del_component_child_event_cb(lv_event_t * e);
//lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
//extern uint32_t LV_EVENT_GET_COMP_CHILD;
//
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
//
//void ui_event_Panel2_Button1(lv_event_t * e);
//extern lv_obj_t * ui_Label1;
//void ui_event_Panel2_Button2(lv_event_t * e);
//extern lv_obj_t * ui_Label3;
//void ui_event_Panel2_Button4(lv_event_t * e);
//extern lv_obj_t * ui_Label4;
//
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
